#!/bin/bash

installDir

# Set the command to execute
cmdToExecute="noelle-load -load ${installDir}/lib/TailCallElim.so --noelle-tailcallelim -mergereturn $1 -o $1"
echo $cmdToExecute ;

# Execute the command
eval $cmdToExecute 
